### ISSUE TITLE
/server modify doesn't find server without freeform port

### ISSUE THREAD

**Issue by vague666** [ailin-nemui/irssi#25]
Expected behavior(imo) v1.3-dev-509-g5953b675-dirty (hilight branch)
```
/server add -tls -network foonet irc.foo.net 6697
irc.foo.net          6697  foonet     tls
/server modify -notls -port 6667 irc.foo.net
irc.foo.net          6667  foonet
```

In v1.3-dev-536-g21701a12 (ssl-flip branch)
```
/server add -tls -network foonet irc.foo.net 6697
irc.foo.net          6697  foonet     disallow_starttls, tls
/server modify -notls -port 6667 irc.foo.net
Server irc.foo.net not found
/server modify -notls -port 6667 irc.foo.net 6697
irc.foo.net          6697  foonet     disallow_starttls
```
port isn't updated when freeform port is included

**Comment by ailin-nemui** [comment]
thanks for thorough testing 😍

**Comment by ailin-nemui** [comment]
to keep the UI "somewhat" sane, -port can no longer be used to change the port. instead, it can be used to choose which of the existing servers you want to edit

**Comment by ailin-nemui** [comment]
I tried to fix it if you want you can test the PR ^
