### ISSUE TITLE
coredump in 1.3-pre

### ISSUE THREAD

**Issue by vague666** [ailin-nemui/irssi#27]
sep 02 08:07:23 irssi systemd-coredump[88505]: Process 88496 (irssi) of user 1000 dumped core.

                                               Stack trace of thread 88496:
                                               #0  0x00007f2a2572653a __strcmp_sse2_unaligned (libc.so.6)
                                               #1  0x000055ef13a0eb9c redirect_match (irssi)
                                               #2  0x000055ef13a0ef6c redirect_find (irssi)
                                               #3  0x000055ef13a0f311 server_redirect_get (irssi)
                                               #4  0x000055ef13a0f3fe server_redirect_get_signal (irssi)
                                               #5  0x000055ef13a0709a irc_server_event (irssi)
                                               #6  0x000055ef139c32d1 signal_emit_real (irssi)
                                               #7  0x000055ef139c3668 signal_emit_id (irssi)
                                               #8  0x000055ef13a0744d irc_server_event_tags (irssi)
                                               #9  0x000055ef139c32d1 signal_emit_real (irssi)
                                               #10 0x000055ef139c3668 signal_emit_id (irssi)
                                               #11 0x000055ef13a076ad irc_parse_incoming_line (irssi)
                                               #12 0x000055ef139c32d1 signal_emit_real (irssi)
                                               #13 0x000055ef139c3668 signal_emit_id (irssi)
                                               #14 0x000055ef13a07755 irc_parse_incoming (irssi)
                                               #15 0x000055ef139b43c8 irssi_io_invoke (irssi)
                                               #16 0x00007f2a267d26aa g_main_context_dispatch (libglib-2.0.so.0)
                                               #17 0x00007f2a267d2a60 n/a (libglib-2.0.so.0)
                                               #18 0x00007f2a267d2b0c g_main_context_iteration (libglib-2.0.so.0)
                                               #19 0x000055ef139959f2 main (irssi)
                                               #20 0x00007f2a256b72e1 __libc_start_main (libc.so.6)
                                               #21 0x000055ef139869fa _start (irssi)

                                               Stack trace of thread 88503:
                                               #0  0x00007f2a257768bd poll (libc.so.6)
                                               #1  0x00007f2a267d29f6 n/a (libglib-2.0.so.0)
                                               #2  0x00007f2a267d2b0c g_main_context_iteration (libglib-2.0.so.0)
                                               #3  0x00007f2a267d2b51 n/a (libglib-2.0.so.0)
                                               #4  0x00007f2a267fa4a5 n/a (libglib-2.0.so.0)
                                               #5  0x00007f2a25a3d4a4 start_thread (libpthread.so.0)
                                               #6  0x00007f2a2577fd0f __clone (libc.so.6)

I'm trying to find the core file but debian or systemd is acting up somehow, I've managed to reproduce the crash several times with my current config. It happens after connecting to libera

**Comment by ailin-nemui** [comment]
thanks!
