### ISSUE TITLE
/hilight -line extra space?

### ISSUE THREAD

**Issue by ailin-nemui** [ailin-nemui/irssi#28]
reported by @vague666

 https://vague.se/pastes/2021-09-02_20%3A04%3A45_478x68_scrot.png

**Comment by vague666** [comment]
dumplines: https://vague.se/pastes/rbKL 
theme: https://vague.se/pastes/dirssi256.theme

**Comment by vague666** [comment]
```
(sep 02 21:46:05) Highlights:
(sep 02 21:46:05)    1 \bvague\b  -line -regexp -color %8%K%7 -actcolor %M
```
